// <auto-generated />
using Benaa2018.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Benaa2018.Data.Migrations
{
    [DbContext(typeof(SBSDbContext))]
    [Migration("20180823190604_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

           

            modelBuilder.Entity("Benaa2018.Data.Model.ToDoMessage", b =>
                {
                    b.Property<int>("ToDo_Message_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<bool>("Is_Owner");

                    b.Property<bool>("Is_Sub");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("ToDo_Details_Id");

                    b.Property<string>("ToDo_Message_Title");

                    b.HasKey("ToDo_Message_Id");

                    b.ToTable("To_Do_Message");
                });

            
#pragma warning restore 612, 618
        }
    }
}
