// <auto-generated />
using Benaa2018.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Benaa2018.Data.Migrations
{
    [DbContext(typeof(SBSDbContext))]
    [Migration("20180830203238_www")]
    partial class www
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

           

           

           
            modelBuilder.Entity("Benaa2018.Data.Model.ToDoAssign", b =>
                {
                    b.Property<int>("ToDoAssignID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<bool>("DeletionStatus");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("ToDoUserAssignTypeId");

                    b.Property<int>("TodoDetailsID");

                    b.Property<int>("UserID");

                    b.HasKey("ToDoAssignID");

                    b.ToTable("To_Do_Assign");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ToDochecklist", b =>
                {
                    b.Property<int>("ToDoCheckListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<bool>("DeletionStatus");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<bool>("ToDoAssignIFilesCheckListItem");

                    b.Property<bool>("ToDoAssignIsCheckListItem");

                    b.Property<int>("TodoDetailsID");

                    b.HasKey("ToDoCheckListId");

                    b.ToTable("To_Do_CheckList");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ToDochecklistDetails", b =>
                {
                    b.Property<int>("ToDochecklistDetailsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<bool>("DeletionStatus");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("ToDoCheckListId");

                    b.Property<string>("ToDoCheckListTitle");

                    b.Property<int>("ToDoCheckListUserId");

                    b.Property<int>("ToDoCheckListUserTypeId");

                    b.Property<bool>("ToDoIsCheckList");

                    b.HasKey("ToDochecklistDetailsId");

                    b.ToTable("To_Do_CheckList_Details");
                });

        

           

            modelBuilder.Entity("Benaa2018.Data.Model.ToDoTag", b =>
                {
                    b.Property<int>("ToDoTagid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<bool>("DeletionStatus");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Tagid");

                    b.Property<int>("TodoDetailsID");

                    b.HasKey("ToDoTagid");

                    b.ToTable("To_Do_Tag");
                });

         
#pragma warning restore 612, 618
        }
    }
}
