// <auto-generated />
using Benaa2018.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Benaa2018.Data.Migrations
{
    [DbContext(typeof(SBSDbContext))]
    [Migration("20180809192703_test2")]
    partial class test2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Benaa2018.Data.Model.CalendarScheduledItem", b =>
                {
                    b.Property<int>("ScheduledItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedTo");

                    b.Property<string>("ColorCode");

                    b.Property<int>("CompanyId");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<int>("Duration");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("EndTime");

                    b.Property<bool>("Hourly");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("ProjectId");

                    b.Property<int>("Reminder");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("StartTime");

                    b.Property<string>("Title");

                    b.HasKey("ScheduledItemId");

                    b.ToTable("Calendar_Scheduled_Item");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.CompanyMaster", b =>
                {
                    b.Property<int>("Org_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company_Name");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.HasKey("Org_ID");

                    b.ToTable("Company_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.DetaildPermission", b =>
                {
                    b.Property<int>("Detaild_Permission_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<int>("Import_Notification_Id");

                    b.Property<bool>("Is_Activity_Remainder_All_Users");

                    b.Property<bool>("Is_Activity_Remainder_Email");

                    b.Property<bool>("Is_Activity_Remainder_Push");

                    b.Property<bool>("Is_Activity_Remainder_Text");

                    b.Property<bool>("Is_Add_All");

                    b.Property<bool>("Is_Admin_Add");

                    b.Property<bool>("Is_Admin_Add_Readonly");

                    b.Property<bool>("Is_Admin_Delete");

                    b.Property<bool>("Is_Admin_Delete_Readonly");

                    b.Property<bool>("Is_Admin_Edit");

                    b.Property<bool>("Is_Admin_Edit_Readonly");

                    b.Property<bool>("Is_Admin_View");

                    b.Property<bool>("Is_Admin_View_Readonly");

                    b.Property<bool>("Is_All_Users");

                    b.Property<bool>("Is_Assigned_To_Lead_Activity_Email");

                    b.Property<bool>("Is_Assigned_To_Lead_Activity_Push");

                    b.Property<bool>("Is_Assigned_To_Lead_Activity_Text");

                    b.Property<bool>("Is_Bid_Accepted_Builder_Email");

                    b.Property<bool>("Is_Bid_Accepted_Builder_Push");

                    b.Property<bool>("Is_Bid_Accepted_Builder_Text");

                    b.Property<bool>("Is_Bid_Discussion_Added_Email");

                    b.Property<bool>("Is_Bid_Discussion_Added_Push");

                    b.Property<bool>("Is_Bid_Discussion_Added_Text");

                    b.Property<bool>("Is_Bid_Resubmitted_Email");

                    b.Property<bool>("Is_Bid_Resubmitted_Push");

                    b.Property<bool>("Is_Bid_Resubmitted_Text");

                    b.Property<bool>("Is_Bid_Submitted_Email");

                    b.Property<bool>("Is_Bid_Submitted_Push");

                    b.Property<bool>("Is_Bid_Submitted_Text");

                    b.Property<bool>("Is_Bids_Add");

                    b.Property<bool>("Is_Bids_Delete");

                    b.Property<bool>("Is_Bids_Edit");

                    b.Property<bool>("Is_Bids_View");

                    b.Property<bool>("Is_Bill_Accounting");

                    b.Property<bool>("Is_Bill_Add");

                    b.Property<bool>("Is_Bill_Cost_Viewing");

                    b.Property<bool>("Is_Bill_Delete");

                    b.Property<bool>("Is_Bill_Edit");

                    b.Property<bool>("Is_Bill_No_Price_Limit");

                    b.Property<bool>("Is_Bill_Payment_Reminder_Email");

                    b.Property<bool>("Is_Bill_View");

                    b.Property<bool>("Is_Calendar_Add");

                    b.Property<bool>("Is_Calendar_Delete");

                    b.Property<bool>("Is_Calendar_Edit");

                    b.Property<bool>("Is_Calendar_View");

                    b.Property<bool>("Is_Change_Order_Approved_Internally_Email");

                    b.Property<bool>("Is_Change_Order_Approved_Internally_Push");

                    b.Property<bool>("Is_Change_Order_Approved_Internally_Text");

                    b.Property<bool>("Is_Change_Order_Discussion_added_All_Users");

                    b.Property<bool>("Is_Change_Order_Discussion_added_Email");

                    b.Property<bool>("Is_Change_Order_Discussion_added_Push");

                    b.Property<bool>("Is_Change_Order_Discussion_added_Text");

                    b.Property<bool>("Is_Change_Order_Past_Due_Email");

                    b.Property<bool>("Is_Change_Order_Past_Due_Text");

                    b.Property<bool>("Is_Change_Order_added_Email");

                    b.Property<bool>("Is_Change_Order_added_Push");

                    b.Property<bool>("Is_Change_Order_added_Text");

                    b.Property<bool>("Is_Change_Order_approved_Email");

                    b.Property<bool>("Is_Change_Order_approved_Push");

                    b.Property<bool>("Is_Change_Order_approved_Text");

                    b.Property<bool>("Is_Change_Order_files_added_Email");

                    b.Property<bool>("Is_Change_Order_files_added_Push");

                    b.Property<bool>("Is_Change_Order_files_added_Text");

                    b.Property<bool>("Is_Change_Orders_Add");

                    b.Property<bool>("Is_Change_Orders_Cost_Viewing");

                    b.Property<bool>("Is_Change_Orders_Delete");

                    b.Property<bool>("Is_Change_Orders_Edit");

                    b.Property<bool>("Is_Change_Orders_View");

                    b.Property<bool>("Is_Customer_Contacts_Add");

                    b.Property<bool>("Is_Customer_Contacts_Add_ReadOnly");

                    b.Property<bool>("Is_Customer_Contacts_Delete");

                    b.Property<bool>("Is_Customer_Contacts_Edit");

                    b.Property<bool>("Is_Customer_Contacts_Export_To_Excel");

                    b.Property<bool>("Is_Customer_Contacts_View");

                    b.Property<bool>("Is_Customer_Contacts_View_ReadOnly");

                    b.Property<bool>("Is_Daily_Log_Discussion_Added_Email");

                    b.Property<bool>("Is_Daily_Log_Notification_Added_Push");

                    b.Property<bool>("Is_Daily_Log_Notification_Added_Text");

                    b.Property<bool>("Is_Daily_Log_Notification_Email");

                    b.Property<bool>("Is_Daily_Log_Notification_Push");

                    b.Property<bool>("Is_Daily_Log_Notification_Text");

                    b.Property<bool>("Is_Delete_All");

                    b.Property<bool>("Is_Document_Comment_added_Email");

                    b.Property<bool>("Is_Document_Comment_added_Push");

                    b.Property<bool>("Is_Document_Comment_added_Text");

                    b.Property<bool>("Is_Documents_Access_SubOwner");

                    b.Property<bool>("Is_Documents_Add");

                    b.Property<bool>("Is_Documents_Delete");

                    b.Property<bool>("Is_Documents_Edit");

                    b.Property<bool>("Is_Documents_Signature");

                    b.Property<bool>("Is_Documents_View");

                    b.Property<bool>("Is_Edit_all");

                    b.Property<bool>("Is_Email_All");

                    b.Property<bool>("Is_Email_Quotes_Alert_Email");

                    b.Property<bool>("Is_Email_Quotes_Alert_Text");

                    b.Property<bool>("Is_Estimate_Accepted_Email");

                    b.Property<bool>("Is_Estimate_Accepted_Text");

                    b.Property<bool>("Is_Estimate_GI_Add");

                    b.Property<bool>("Is_Estimate_GI_Delete");

                    b.Property<bool>("Is_Estimate_GI_Edit");

                    b.Property<bool>("Is_Estimate_GI_Price_Viewing");

                    b.Property<bool>("Is_Estimate_GI_View");

                    b.Property<bool>("Is_Estimate_Viewed_Email");

                    b.Property<bool>("Is_Estimate_Viewed_Text");

                    b.Property<bool>("Is_Job_Info_Add");

                    b.Property<bool>("Is_Job_Info_Edit");

                    b.Property<bool>("Is_Job_Info_View");

                    b.Property<bool>("Is_Job_Info_delete");

                    b.Property<bool>("Is_Lead_Notify_Email");

                    b.Property<bool>("Is_Lead_Notify_Push");

                    b.Property<bool>("Is_Lead_Notify_Text");

                    b.Property<bool>("Is_Lead_Proposal_Accepted_All_Users");

                    b.Property<bool>("Is_Lead_Proposal_Accepted_Email");

                    b.Property<bool>("Is_Lead_Proposal_Accepted_Push");

                    b.Property<bool>("Is_Lead_Proposal_Accepted_Text");

                    b.Property<bool>("Is_Lead_Proposal_Viewed_Email");

                    b.Property<bool>("Is_Lead_Proposal_Viewed_Push");

                    b.Property<bool>("Is_Lead_Proposal_Viewed_Text");

                    b.Property<bool>("Is_Leads_Add");

                    b.Property<bool>("Is_Leads_Assign_Salesperson");

                    b.Property<bool>("Is_Leads_Convert_To_Jobsite");

                    b.Property<bool>("Is_Leads_Delete");

                    b.Property<bool>("Is_Leads_Edit");

                    b.Property<bool>("Is_Leads_Export_To_Excel");

                    b.Property<bool>("Is_Leads_View");

                    b.Property<bool>("Is_Leads_View_Other_Salesperson");

                    b.Property<bool>("Is_Lien_Waiver_Accepted_Email");

                    b.Property<bool>("Is_Lien_Waiver_Accepted_Text");

                    b.Property<bool>("Is_Lien_Waiver_Declined_Email");

                    b.Property<bool>("Is_Lien_Waiver_Declined_Text");

                    b.Property<bool>("Is_Linked_Clicked_By_Lead_Email");

                    b.Property<bool>("Is_Linked_Clicked_By_Lead_Text");

                    b.Property<bool>("Is_Logs_Add");

                    b.Property<bool>("Is_Logs_Delete");

                    b.Property<bool>("Is_Logs_Edit");

                    b.Property<bool>("Is_Logs_View");

                    b.Property<bool>("Is_Message_Global");

                    b.Property<bool>("Is_Messages_Add");

                    b.Property<bool>("Is_Messages_Add_Readonly");

                    b.Property<bool>("Is_Messages_Delete");

                    b.Property<bool>("Is_Messages_Edit");

                    b.Property<bool>("Is_Messages_Edit_Readonly");

                    b.Property<bool>("Is_Messages_View");

                    b.Property<bool>("Is_New_Lead_Email");

                    b.Property<bool>("Is_New_Lead_Push");

                    b.Property<bool>("Is_New_Lead_Text");

                    b.Property<bool>("Is_New_Message_All_Users");

                    b.Property<bool>("Is_New_Message_Email");

                    b.Property<bool>("Is_New_Message_Push");

                    b.Property<bool>("Is_New_Message_Text");

                    b.Property<bool>("Is_Other_Employee_Contact_Email");

                    b.Property<bool>("Is_Other_Employee_Contact_Text");

                    b.Property<bool>("Is_Over_Time_Reached_All_Users");

                    b.Property<bool>("Is_Over_Time_Reached_Email");

                    b.Property<bool>("Is_Over_Time_Reached_Push");

                    b.Property<bool>("Is_Over_Time_Reached_Text");

                    b.Property<bool>("Is_Owner_Activated_Email");

                    b.Property<bool>("Is_Owner_Payment_Added_Email");

                    b.Property<bool>("Is_Owner_Payment_Added_Push");

                    b.Property<bool>("Is_Owner_Payment_Added_Text");

                    b.Property<bool>("Is_Owner_Payment_Discussion_Email");

                    b.Property<bool>("Is_Owner_Payment_Discussion_Push");

                    b.Property<bool>("Is_Owner_Payment_Discussion_Text");

                    b.Property<bool>("Is_Owner_Payment_Past_Due_Email");

                    b.Property<bool>("Is_Owner_Payment_Past_Due_Push");

                    b.Property<bool>("Is_Owner_Payment_Past_Due_Text");

                    b.Property<bool>("Is_Owner_Payment_Reminder_Email");

                    b.Property<bool>("Is_Owner_Payment_Reminder_Push");

                    b.Property<bool>("Is_Owner_Payment_Reminder_Text");

                    b.Property<bool>("Is_Owner_Payment_Updated_Email");

                    b.Property<bool>("Is_Owner_Payment_Updated_Push");

                    b.Property<bool>("Is_Owner_Payment_Updated_Text");

                    b.Property<bool>("Is_Owner_Payments_Add");

                    b.Property<bool>("Is_Owner_Payments_Delete");

                    b.Property<bool>("Is_Owner_Payments_Edit");

                    b.Property<bool>("Is_Owner_Payments_View");

                    b.Property<bool>("Is_Owner_Requested_Change_Order_Email");

                    b.Property<bool>("Is_Owner_Requested_Change_Order_Push");

                    b.Property<bool>("Is_Owner_Requested_Change_Order_Text");

                    b.Property<bool>("Is_Owner_Sumitted_Survey_Email");

                    b.Property<bool>("Is_Owner_Sumitted_Survey_Text");

                    b.Property<bool>("Is_PO_Approved_Email");

                    b.Property<bool>("Is_PO_Approved_Internally_Email");

                    b.Property<bool>("Is_PO_Approved_Internally_Push");

                    b.Property<bool>("Is_PO_Approved_Internally_Text");

                    b.Property<bool>("Is_PO_Approved_Push");

                    b.Property<bool>("Is_PO_Approved_Text");

                    b.Property<bool>("Is_PO_Assigned_Internally_Email");

                    b.Property<bool>("Is_PO_Assigned_Internally_Text");

                    b.Property<bool>("Is_PO_Declined_Email");

                    b.Property<bool>("Is_PO_Declined_Push");

                    b.Property<bool>("Is_PO_Declined_Text");

                    b.Property<bool>("Is_PO_Discussion_Added_Email");

                    b.Property<bool>("Is_PO_Discussion_Added_Push");

                    b.Property<bool>("Is_PO_Discussion_Added_Text");

                    b.Property<bool>("Is_PO_File_Added_Email");

                    b.Property<bool>("Is_PO_Inspection_Email");

                    b.Property<bool>("Is_PO_Inspection_Push");

                    b.Property<bool>("Is_PO_Inspection_Reminder_Email");

                    b.Property<bool>("Is_PO_Inspection_Reminder_Push");

                    b.Property<bool>("Is_PO_Inspection_Reminder_Text");

                    b.Property<bool>("Is_PO_Payment_Made_Email");

                    b.Property<bool>("Is_PO_Payment_Marked_Email");

                    b.Property<bool>("Is_PO_Work_Complete_Email");

                    b.Property<bool>("Is_PO_Work_Complete_Push");

                    b.Property<bool>("Is_PO_Work_Complete_Text");

                    b.Property<bool>("Is_PO_Work_completed_Email");

                    b.Property<bool>("Is_Photo_Comment_Added_Email");

                    b.Property<bool>("Is_Photo_Comment_Added_Push");

                    b.Property<bool>("Is_Photo_Comment_Added_Text");

                    b.Property<bool>("Is_Photos_Add");

                    b.Property<bool>("Is_Photos_Delete");

                    b.Property<bool>("Is_Photos_Edit");

                    b.Property<bool>("Is_Photos_View");

                    b.Property<bool>("Is_Price_Viewing");

                    b.Property<bool>("Is_Push_On");

                    b.Property<bool>("Is_RFI_Add");

                    b.Property<bool>("Is_RFI_Added_By_Builder_Email");

                    b.Property<bool>("Is_RFI_Added_By_Builder_Push");

                    b.Property<bool>("Is_RFI_Added_By_Builder_Text");

                    b.Property<bool>("Is_RFI_Added_Email");

                    b.Property<bool>("Is_RFI_Added_Push");

                    b.Property<bool>("Is_RFI_Added_Text");

                    b.Property<bool>("Is_RFI_Completed_Email");

                    b.Property<bool>("Is_RFI_Completed_Push");

                    b.Property<bool>("Is_RFI_Completed_Text");

                    b.Property<bool>("Is_RFI_Edit");

                    b.Property<bool>("Is_RFI_Past_Due_Email");

                    b.Property<bool>("Is_RFI_Past_Due_Text");

                    b.Property<bool>("Is_RFI_Response_Added_Email");

                    b.Property<bool>("Is_RFI_Response_Added_Push");

                    b.Property<bool>("Is_RFI_Response_Added_Text");

                    b.Property<bool>("Is_RFI_View");

                    b.Property<bool>("Is_RFI__Delete");

                    b.Property<bool>("Is_Schedule_Item_Discussion_All_Users");

                    b.Property<bool>("Is_Schedule_Item_Discussion_Email");

                    b.Property<bool>("Is_Schedule_Item_Discussion_Push");

                    b.Property<bool>("Is_Schedule_Item_Discussion_Text");

                    b.Property<bool>("Is_Selection_Approved_Email");

                    b.Property<bool>("Is_Selection_Approved_Internally_Email");

                    b.Property<bool>("Is_Selection_Approved_Internally_Push");

                    b.Property<bool>("Is_Selection_Approved_Internally_Text");

                    b.Property<bool>("Is_Selection_Approved_Push");

                    b.Property<bool>("Is_Selection_Approved_Text");

                    b.Property<bool>("Is_Selection_Choice_Added_Email");

                    b.Property<bool>("Is_Selection_Choice_Added_Push");

                    b.Property<bool>("Is_Selection_Choice_Added_Text");

                    b.Property<bool>("Is_Selection_Deadline_Reminder_Email");

                    b.Property<bool>("Is_Selection_Deadline_Reminder_Push");

                    b.Property<bool>("Is_Selection_Discussion_Added_Email");

                    b.Property<bool>("Is_Selection_Discussion_Added_Push");

                    b.Property<bool>("Is_Selection_Discussion_Added_Text");

                    b.Property<bool>("Is_Selection_Owner_Price_Email");

                    b.Property<bool>("Is_Selection_Owner_Price_Push");

                    b.Property<bool>("Is_Selection_Owner_Price_Text");

                    b.Property<bool>("Is_Selection_Sub_Price_Email");

                    b.Property<bool>("Is_Selection_Sub_Price_Push");

                    b.Property<bool>("Is_Selection_Sub_Price_Text");

                    b.Property<bool>("Is_Selections_Add");

                    b.Property<bool>("Is_Selections_Cost_Viewing");

                    b.Property<bool>("Is_Selections_Delete");

                    b.Property<bool>("Is_Selections_Edit");

                    b.Property<bool>("Is_Selections_View");

                    b.Property<bool>("Is_Set_Baseline");

                    b.Property<bool>("Is_Signature_Request_Past_Due_Email");

                    b.Property<bool>("Is_Signature_Request_Past_Due_Push");

                    b.Property<bool>("Is_Signature_Request_Signed_Email");

                    b.Property<bool>("Is_Signature_Request_Signed_Push");

                    b.Property<bool>("Is_Sub_Activated_Email");

                    b.Property<bool>("Is_Sub_And_Owner_Uploaded_Email");

                    b.Property<bool>("Is_Sub_And_Owner_Uploaded_Push");

                    b.Property<bool>("Is_Sub_And_Owner_Uploaded_Text");

                    b.Property<bool>("Is_Sub_Confirmation_Email");

                    b.Property<bool>("Is_Sub_Confirmation_Push");

                    b.Property<bool>("Is_Sub_Confirmation_Text");

                    b.Property<bool>("Is_Sub_Insurance_Remider_Email");

                    b.Property<bool>("Is_Subs_Add");

                    b.Property<bool>("Is_Subs_Delete");

                    b.Property<bool>("Is_Subs_Edit");

                    b.Property<bool>("Is_Subs_View");

                    b.Property<bool>("Is_Survey_Add");

                    b.Property<bool>("Is_Survey_Add_Review_Website");

                    b.Property<bool>("Is_Survey_Delete");

                    b.Property<bool>("Is_Survey_Edit");

                    b.Property<bool>("Is_Survey_View");

                    b.Property<bool>("Is_Text_All");

                    b.Property<bool>("Is_Time_Clock_Add");

                    b.Property<bool>("Is_Time_Clock_Adjust_Other_User");

                    b.Property<bool>("Is_Time_Clock_Cost_Viewing");

                    b.Property<bool>("Is_Time_Clock_Delete");

                    b.Property<bool>("Is_Time_Clock_Edit");

                    b.Property<bool>("Is_Time_Clock_Review_And_Approve");

                    b.Property<bool>("Is_Time_Clock_View");

                    b.Property<bool>("Is_Time_Clock_View_Other_User");

                    b.Property<bool>("Is_Time_Sheet_Adjustment_All_Users");

                    b.Property<bool>("Is_Time_Sheet_Adjustment_Email");

                    b.Property<bool>("Is_Time_Sheet_Adjustment_Push");

                    b.Property<bool>("Is_Time_Sheet_Adjustment_Text");

                    b.Property<bool>("Is_To_Do_Add");

                    b.Property<bool>("Is_To_Do_Assign_Users");

                    b.Property<bool>("Is_To_Do_Completed_Email");

                    b.Property<bool>("Is_To_Do_Completed_Push");

                    b.Property<bool>("Is_To_Do_Completed_Text");

                    b.Property<bool>("Is_To_Do_Delete");

                    b.Property<bool>("Is_To_Do_Discussion_Added_Email");

                    b.Property<bool>("Is_To_Do_Discussion_Added_Push");

                    b.Property<bool>("Is_To_Do_Discussion_Added_Text");

                    b.Property<bool>("Is_To_Do_Edit");

                    b.Property<bool>("Is_To_Do_Global");

                    b.Property<bool>("Is_To_Do_View");

                    b.Property<bool>("Is_Trade_Agreement_Action_Taken_Email");

                    b.Property<bool>("Is_User_Confirmed_Change_Email");

                    b.Property<bool>("Is_User_Confirmed_Change_Push");

                    b.Property<bool>("Is_User_Confirmed_Change_Text");

                    b.Property<bool>("Is_User_Declined_Change_Email");

                    b.Property<bool>("Is_User_Declined_Change_Push");

                    b.Property<bool>("Is_User_Declined_Change_Text");

                    b.Property<bool>("Is_User_Need_To_Confirm_Change_Email");

                    b.Property<bool>("Is_User_Need_To_Confirm_Change_Push");

                    b.Property<bool>("Is_User_Need_To_Confirm_Change_Text");

                    b.Property<bool>("Is_Video_Comment_Added_Email");

                    b.Property<bool>("Is_Video_Comment_Added_Push");

                    b.Property<bool>("Is_Video_Comment_Added_Text");

                    b.Property<bool>("Is_Videos_Add");

                    b.Property<bool>("Is_Videos_Delete");

                    b.Property<bool>("Is_Videos_Edit");

                    b.Property<bool>("Is_Videos_View");

                    b.Property<bool>("Is_View_All");

                    b.Property<bool>("Is_View_All_Customer_Contacts");

                    b.Property<bool>("Is_View_All_Customer_Contacts_Readonly");

                    b.Property<bool>("Is_View_Owner_Site");

                    b.Property<bool>("Is_Warranty_Add");

                    b.Property<bool>("Is_Warranty_Added_Email");

                    b.Property<bool>("Is_Warranty_Added_Internally_Email");

                    b.Property<bool>("Is_Warranty_Added_Internally_Push");

                    b.Property<bool>("Is_Warranty_Added_Internally_Text");

                    b.Property<bool>("Is_Warranty_Added_Push");

                    b.Property<bool>("Is_Warranty_Added_Text");

                    b.Property<bool>("Is_Warranty_Delete");

                    b.Property<bool>("Is_Warranty_Discussion_Added_All_Users");

                    b.Property<bool>("Is_Warranty_Discussion_Added_Email");

                    b.Property<bool>("Is_Warranty_Discussion_Added_Push");

                    b.Property<bool>("Is_Warranty_Discussion_Added_Text");

                    b.Property<bool>("Is_Warranty_Edit");

                    b.Property<bool>("Is_Warranty_Follow_Up_All_Users");

                    b.Property<bool>("Is_Warranty_Follow_Up_Email");

                    b.Property<bool>("Is_Warranty_Follow_Up_Text");

                    b.Property<bool>("Is_Warranty_Has_Feedback_Email");

                    b.Property<bool>("Is_Warranty_Schedule_Changed_Email");

                    b.Property<bool>("Is_Warranty_Schedule_Changed_Text");

                    b.Property<bool>("Is_Warranty_Service_Internally_Assigned_Email");

                    b.Property<bool>("Is_Warranty_Service_Internally_Assigned_Text");

                    b.Property<bool>("Is_Warranty_Updated_Appt_Email");

                    b.Property<bool>("Is_Warranty_Updated_Appt_Text");

                    b.Property<bool>("Is_Warranty_Updated_Email");

                    b.Property<bool>("Is_Warranty_Updated_Text");

                    b.Property<bool>("Is_Warranty_View");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("User_ID");

                    b.HasKey("Detaild_Permission_Id");

                    b.ToTable("Detaild_Permission");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.LoginDetailsInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastLoginDate");

                    b.Property<DateTime>("LoginDateTime");

                    b.HasKey("UserId");

                    b.ToTable("Login_Details_Info");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.MenuMaster", b =>
                {
                    b.Property<int>("Menu_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("CssClass");

                    b.Property<bool>("Delflag");

                    b.Property<string>("Menu_Name");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("PatentId");

                    b.HasKey("Menu_ID");

                    b.ToTable("Menu_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.OwnerMaster", b =>
                {
                    b.Property<int>("Owner_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessMethod");

                    b.Property<bool>("Active");

                    b.Property<string>("Address");

                    b.Property<bool>("AllowLockedSelections");

                    b.Property<bool>("AllowOrderRequests");

                    b.Property<bool>("AllowPaymentsTab");

                    b.Property<bool>("AllowWarrantyClaims");

                    b.Property<string>("City");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Email");

                    b.Property<string>("Mobile_No");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Org_ID");

                    b.Property<string>("OwnerActivation");

                    b.Property<string>("OwnerCalendar");

                    b.Property<string>("OwnerInformation");

                    b.Property<string>("Owner_Name");

                    b.Property<string>("Profile_Picture");

                    b.Property<int>("Project_ID");

                    b.Property<bool>("ShowBudgetPurchaseOrders");

                    b.Property<bool>("ShowProjectPrice");

                    b.Property<string>("State");

                    b.Property<string>("Telephone");

                    b.Property<string>("Zip");

                    b.HasKey("Owner_ID");

                    b.ToTable("Owner_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.PredecessorInformation", b =>
                {
                    b.Property<int>("PredecessorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<int>("Lag");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("ProjectId");

                    b.Property<int>("ScheduledItemId");

                    b.Property<string>("TimeFrame");

                    b.HasKey("PredecessorId");

                    b.ToTable("Predecessor_Information");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ProjectColorMaster", b =>
                {
                    b.Property<int>("ProjectColorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ColorCode");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<bool>("IsDisable");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<string>("ProjectColorName");

                    b.HasKey("ProjectColorId");

                    b.ToTable("Project_Color");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ProjectGroup", b =>
                {
                    b.Property<int>("Project_Goup_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<string>("Project_Group_Name");

                    b.Property<int>("User_ID");

                    b.HasKey("Project_Goup_ID");

                    b.ToTable("Project_Group");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ProjectManagerMaster", b =>
                {
                    b.Property<int>("Manager_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Manager_Name");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Org_ID");

                    b.HasKey("Manager_ID");

                    b.ToTable("Project_Manager_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ProjectMaster", b =>
                {
                    b.Property<int>("Project_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Address");

                    b.Property<float>("Built_Up_Area");

                    b.Property<string>("City");

                    b.Property<decimal>("Contract_Price");

                    b.Property<decimal>("Country_ID");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Group_No");

                    b.Property<string>("Internal_Notes");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Lot_Info");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("No_Of_Unit");

                    b.Property<long>("Org_ID");

                    b.Property<string>("Permit_No");

                    b.Property<string>("Project_Group_ID");

                    b.Property<string>("Project_Manager_id");

                    b.Property<string>("Project_Name");

                    b.Property<string>("Project_Prefix");

                    b.Property<int>("Project_Type_ID");

                    b.Property<float>("Project_land_Cost");

                    b.Property<int>("Sequence");

                    b.Property<string>("State");

                    b.Property<int>("Status_ID");

                    b.Property<string>("Sub_Notes");

                    b.Property<int>("User_ID");

                    b.Property<string>("Zip");

                    b.HasKey("Project_ID");

                    b.ToTable("Project_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ProjectScheduleMaster", b =>
                {
                    b.Property<int>("Schedule_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Actual_Completion");

                    b.Property<DateTime>("Actual_Start");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Org_ID");

                    b.Property<string>("ProjectColorId");

                    b.Property<string>("Project_Color_ID");

                    b.Property<int>("Project_ID");

                    b.Property<DateTime>("Projected_Completion");

                    b.Property<DateTime>("Projected_Start");

                    b.Property<string>("Works_Days");

                    b.HasKey("Schedule_ID");

                    b.ToTable("Project_schedule_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ProjectStatusMaster", b =>
                {
                    b.Property<int>("Status_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Org_ID");

                    b.Property<string>("Status_Name");

                    b.HasKey("Status_ID");

                    b.ToTable("Project_Status_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ProjectSubcontractorConfig", b =>
                {
                    b.Property<int>("SubContractor_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Org_ID");

                    b.Property<decimal>("Project_ID");

                    b.Property<string>("Subcontractor_Name");

                    b.Property<bool>("View_Access");

                    b.HasKey("SubContractor_ID");

                    b.ToTable("Project_Subcontractor_config");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ProjectTypeMaster", b =>
                {
                    b.Property<int>("Project_Type_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Org_ID");

                    b.Property<string>("Project_Type_Name");

                    b.HasKey("Project_Type_ID");

                    b.ToTable("Project_Type_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ProjectUserIntConfigMaster", b =>
                {
                    b.Property<int>("Internal_User_Con_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Org_ID");

                    b.Property<int>("Project_ID");

                    b.Property<bool>("Recive_Notification");

                    b.Property<int>("UserID");

                    b.Property<string>("User_Name");

                    b.Property<bool>("View_Access");

                    b.HasKey("Internal_User_Con_Id");

                    b.ToTable("Project_User_Int_Config_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.SubContractorMaster", b =>
                {
                    b.Property<int>("SubContractor_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Beneficiary");

                    b.Property<string>("CR_NO");

                    b.Property<decimal>("Catogery_ID");

                    b.Property<string>("Contact_Persion");

                    b.Property<int>("Country_ID");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Email");

                    b.Property<string>("Fax");

                    b.Property<string>("Mobile");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<string>("Name");

                    b.Property<int>("Org_ID");

                    b.Property<string>("Tel");

                    b.HasKey("SubContractor_ID");

                    b.ToTable("SubContractor_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.TagMaster", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<string>("TagName");

                    b.HasKey("TagId");

                    b.ToTable("Tag_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ToDochecklist", b =>
                {
                    b.Property<int>("ToDoCheckListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<bool>("ToDoAssignIFilesCheckListItem");

                    b.Property<bool>("ToDoAssignIsCheckListItem");

                    b.Property<int>("TodoDetailsID");

                    b.HasKey("ToDoCheckListId");

                    b.ToTable("To_Do_CheckList");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ToDochecklistDetails", b =>
                {
                    b.Property<int>("ToDochecklistDetailsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("ToDoCheckListId");

                    b.Property<string>("ToDoCheckListTitle");

                    b.Property<int>("ToDoCheckListUserId");

                    b.Property<int>("ToDoCheckListUserTypeId");

                    b.Property<bool>("ToDoIsCheckList");

                    b.HasKey("ToDochecklistDetailsId");

                    b.ToTable("To_Do_CheckList_Details");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ToDoMaster", b =>
                {
                    b.Property<int>("Todo_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignTo");

                    b.Property<DateTime>("Assign_Date");

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<int>("Days");

                    b.Property<DateTime>("Due_Date_Selection");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<string>("Note");

                    b.Property<int>("Org_ID");

                    b.Property<string>("Priority");

                    b.Property<int>("Project_ID");

                    b.Property<string>("Project_Site");

                    b.Property<int>("Reminder_ID");

                    b.Property<int>("Schedule_ID");

                    b.Property<int>("TaG_ID");

                    b.Property<int>("Time_choosen_ID");

                    b.Property<string>("Title");

                    b.Property<string>("state_val");

                    b.HasKey("Todo_ID");

                    b.ToTable("To_Do_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ToDoMasterDetails", b =>
                {
                    b.Property<int>("TodoDetailsID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<bool>("DeletionStatus");

                    b.Property<string>("DueDatetime");

                    b.Property<DateTime>("Duedate");

                    b.Property<bool>("IsMarkedComplete");

                    b.Property<DateTime>("LinkToDate");

                    b.Property<string>("LinkToDaysStatus");

                    b.Property<string>("LinkToTime");

                    b.Property<int>("LinkToUnit");

                    b.Property<int>("LinkToWorkId");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Org_ID");

                    b.Property<string>("Priority");

                    b.Property<int>("Project_ID");

                    b.Property<string>("Project_Site");

                    b.Property<int>("ReminderId");

                    b.Property<string>("Title");

                    b.Property<string>("TypeNote");

                    b.HasKey("TodoDetailsID");

                    b.ToTable("To_Do_Master_Details");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.ToDoTag", b =>
                {
                    b.Property<int>("ToDoTagid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Tagid");

                    b.Property<int>("TodoDetailsID");

                    b.HasKey("ToDoTagid");

                    b.ToTable("To_Do_Tag");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.UserMaster", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("FullName");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("Org_ID");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.Property<int>("User_Alert_Schedule");

                    b.Property<string>("User_Cell_Email");

                    b.Property<string>("User_Contact_Info");

                    b.Property<string>("User_Default_Labour_Cost");

                    b.Property<int>("User_Default_Time_Clock");

                    b.Property<string>("User_Email");

                    b.Property<bool>("User_Enabled");

                    b.Property<string>("User_First_Name");

                    b.Property<string>("User_Forum_Handle");

                    b.Property<bool>("User_Is_Alert");

                    b.Property<bool>("User_Is_Automatic_Access");

                    b.Property<bool>("User_Is_Forum_Handle");

                    b.Property<string>("User_Last_Name");

                    b.Property<bool>("User_Login_Enabled");

                    b.Property<string>("User_Phone");

                    b.HasKey("UserID");

                    b.ToTable("User_Master");
                });

            modelBuilder.Entity("Benaa2018.Data.Model.WarrentyAlert", b =>
                {
                    b.Property<int>("Warrent_Alert_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<int>("User_ID");

                    b.Property<string>("Warrenty_Name");

                    b.Property<int>("Warrenty_Year");

                    b.HasKey("Warrent_Alert_Id");

                    b.ToTable("Warrenty_Alert");
                });
#pragma warning restore 612, 618
        }
    }
}
