// <auto-generated />
using Benaa2018.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Benaa2018.Data.Migrations
{
    [DbContext(typeof(SBSDbContext))]
    partial class SBSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

           

          

           
           
          

            modelBuilder.Entity("Benaa2018.Data.Model.TagMaster", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created_By");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("Modified_By");

                    b.Property<DateTime>("Modified_Date");

                    b.Property<string>("TagName");

                    b.HasKey("TagId");

                    b.ToTable("Tag_Master");
                });

            
#pragma warning restore 612, 618
        }
    }
}
